name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup pnpm
                # You may pin to the exact commit or the version.
                # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
              uses: pnpm/action-setup@v2.2.4
              with:
                run_install: true
            - name: Install and Build 🔧
              env:
                  BASE_PATH: /the-pocket-gita
              run: |
                  pnpm build
                  touch ./out/.nojekyll

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.7
              with:
                  branch: gh-pages
                  folder: out
